"""Add CartItem Model

Revision ID: 601a258b0668
Revises: f265c6b07cd4
Create Date: 2024-10-06 22:19:32.752514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '601a258b0668'
down_revision: Union[str, None] = 'f265c6b07cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartitems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('carts_product_id_fkey', 'carts', type_='foreignkey')
    op.drop_column('carts', 'quantity')
    op.drop_column('carts', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('carts', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('carts_product_id_fkey', 'carts', 'products', ['product_id'], ['id'])
    op.drop_table('cartitems')
    # ### end Alembic commands ###
